[book]
authors = ["CompEng0001"]
language = "en"
multilingual = false
src = "src"
title = "Programming for Engineers"

[preprocessor.pagetoc]
[output.html]
mathjax-support = true
git-repository-url = "https://github.com/uniofgreenwich/ELEE1147_Exercises"
edit-url-template = "https://github.com/uniofgreenwich/ELEE1147_Exercises/edit/main/{path}"
additional-css = ["theme/pagetoc.css"]
additional-js  = ["theme/pagetoc.js"]

[output.html.search]
limit-results = 20
use-boolean-and = true
boost-title = 2
boost-hierarchy = 2
boost-paragraph = 1
expand = true
heading-split-level = 2

[output.html.fold]
enable = true

[output.html.print]
enable = false
